// Authorize.Net ARB (Automated Recurring Billing). ARB stores only an
// amount + schedule — OUR database remains the source of truth for plan,
// price arm, status and period boundaries (Rule 9). We reference the stored
// Customer Profile so the same card recurs and can be updated later.
import { anetPost } from "./client";
import { statementDescriptor } from "./env";

function todayISO(): string {
  // ARB startDate must be today or later, format YYYY-MM-DD (UTC).
  return new Date().toISOString().slice(0, 10);
}

export interface CreatedSubscription {
  subscriptionId: string;
}

// NOTE: an Accept.js opaque nonce CANNOT fund ARBCreateSubscription directly —
// Authorize.Net returns E00114 "Invalid OTS Token" (verified against the live
// sandbox, twice). The nonce must first be turned into a Customer Profile
// (createCustomerProfileFromOpaque); ARB then charges that stored profile.

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

export async function createMonthlySubscription(opts: {
  amountCents: number;
  customerProfileId: string;
  customerPaymentProfileId: string;
  subscriptionName?: string;
  // E00040-retry tuning (defaults chosen for production; tests override to run fast)
  retryAttempts?: number;
  retryDelayMs?: number;
}): Promise<CreatedSubscription> {
  const retryAttempts = opts.retryAttempts ?? 8;
  const retryDelayMs = opts.retryDelayMs ?? 1500;
  const amount = (opts.amountCents / 100).toFixed(2);
  // NOTE: when charging a stored customer/payment profile, ARB does NOT accept
  // a billTo in the request (E00093). The billing name lives ON the payment
  // profile, set when it was created (see createCustomerProfileFromOpaque).
  const body = {
    subscription: {
      name: (opts.subscriptionName || statementDescriptor()).slice(0, 50),
      paymentSchedule: {
        interval: { length: 1, unit: "months" },
        startDate: todayISO(),
        totalOccurrences: 9999, // "until canceled"
      },
      amount,
      profile: {
        customerProfileId: opts.customerProfileId,
        customerPaymentProfileId: opts.customerPaymentProfileId,
      },
    },
  };

  // A just-created customer/payment profile isn't immediately visible to ARB
  // (E00040 "record cannot be found"). This is a create-then-subscribe race in
  // the same request; retry with backoff until the profile lands. The lag is a
  // sandbox-testMode artifact expected to be absent under production liveMode
  // (which validates the card with a real auth, materializing the profile).
  let res = await anetPost("ARBCreateSubscriptionRequest", body);
  for (let attempt = 0; attempt < retryAttempts && !res.ok && anetCode(res) === "E00040"; attempt++) {
    await sleep(retryDelayMs);
    res = await anetPost("ARBCreateSubscriptionRequest", body);
  }

  if (!res.ok || !res.raw.subscriptionId) {
    const all = res.raw?.messages?.message;
    const detail = Array.isArray(all) ? all.map((m: any) => `${m.code}:${m.text}`).join(" | ") : `${res.code || ""} ${res.text || ""}`;
    throw new Error(`Authorize.Net ARB error: ${detail} (profile=${opts.customerProfileId} payment=${opts.customerPaymentProfileId})`.trim());
  }
  return { subscriptionId: String(res.raw.subscriptionId) };
}

function anetCode(res: { raw?: any; code?: string }): string {
  const m = res.raw?.messages?.message;
  return (Array.isArray(m) ? m[0]?.code : m?.code) || res.code || "";
}

export async function cancelSubscription(subscriptionId: string): Promise<void> {
  const res = await anetPost("ARBCancelSubscriptionRequest", { subscriptionId });
  if (!res.ok) throw new Error(`Authorize.Net cancel error: ${res.code || ""} ${res.text || ""}`.trim());
}

export async function getSubscriptionStatus(subscriptionId: string): Promise<string> {
  const res = await anetPost("ARBGetSubscriptionStatusRequest", { subscriptionId });
  return res.raw?.status || "unknown";
}

export interface TxnSubscriptionInfo {
  subscriptionId: string | null;
  payNum: number | null;
  amountCents: number;
  submitTimeUTC: string | null;
  cardBrand: string | null;
  last4: string | null;
}

// Look up a transaction and, if it was generated by an ARB subscription,
// return the subscription id + masked card so a recurring-charge webhook can
// be tied back to our subscription row (webhooks only carry the transId).
export async function getTransactionSubscription(transId: string): Promise<TxnSubscriptionInfo | null> {
  const res = await anetPost("getTransactionDetailsRequest", { transId });
  if (!res.ok) return null;
  const t = res.raw?.transaction;
  if (!t) return null;
  const cc = t.payment?.creditCard;
  const amt = parseFloat(t.authAmount ?? t.settleAmount ?? "0");
  return {
    subscriptionId: t.subscription?.id != null ? String(t.subscription.id) : null,
    payNum: t.subscription?.payNum != null ? Number(t.subscription.payNum) : null,
    amountCents: Math.round((Number.isFinite(amt) ? amt : 0) * 100),
    submitTimeUTC: t.submitTimeUTC || null,
    cardBrand: cc?.cardType || null,
    last4: cc?.cardNumber ? String(cc.cardNumber).replace(/[^0-9]/g, "").slice(-4) : null,
  };
}
